name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -P build-cli-jar

      - name: Create release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/oashield-*.jar
            target/oashield-cli.jar

      - name: Set up GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --import-ownertrust

      - name: Deploy to Maven Central
        run: mvn deploy -P build-cli-jar -DskipTests --settings .github/maven-settings.xml

      - name: Update version in pom.xml
        run: |
          new_version=$(echo ${{ github.ref }} | sed 's/v//')
          mvn versions:set -DnewVersion=$new_version
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add pom.xml
          git commit -m "Update version to $new_version"
          git push origin HEAD:main
